apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-server
template:
  metadata:
    name: simple-server     
  labels:
    role: say-hello
    app: deploy-server
    maintainer: Muhammad Haris Shafiq
    email: harisshafiq08@gmail.com
  annotations:
    description: This application is the main server written in go lang which listens and Servers requests on 8083 
  spec:
    containers:
    - image: server:latest
      name: server
      ports:
      - containerPort: 8083
      env:
      - name: MYNAMEc
        value: "Haris"
      imagePullPolicy: IfNotPresent
strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
